### PR TITLE
Add memory wiping functionality

### PR DESCRIPTION
**Pull request by ionut-arm**
This commit improves the security of the library by wiping out all
sensitive data before it is dropped.

Signed-off-by: Ionut Mihalcea <ionut.mihalcea@arm.com>

### CODE REVIEW

**Comment by hug-dev** [comment]
I know that we came to the conclusion that it was ok to have `Secret` and `Zeroizing` on the interface but I am now thinking about it. Is it such a good idea? I definitely agree that we need to internally use them to clear our memory but should we do impose that on the client? Maybe in its threat model, the client does not need memory wiping and having those type in the interface will be come a burden.

I am also thinking about #31: could we kill two birds with one stone? As in both:
1. use references for sensitive data (references of `Vec<u8>`)
2. let the user handle zeroizing of memory of its owned structures
3. whenever we clone it ourselves, we do zeroize it

For 1, if we have in our interface `&Vec<u8>`, can a client use it with `Zeroizing` or `Secret`? I think so both with the `Deref` implementation and with `expose_secret`.

**Comment by ionut-arm** [comment]
Yep, totally agree with that, we can, in the future, add the `Zeroizing` and `Secret` as a layer in our client, the `BasicClient` can just stay... basic.

**Comment by ionut-arm** [comment]
Should we still use `Secret` in the authentication token, though? I'd say yes, in which case we have to export the `secrecy` crate as well. It' just the `BasicClient` that stays the same.

**Comment by hug-dev** [comment]
> Should we still use Secret in the authentication token, though? I'd say yes, in which case we have to export the secrecy crate as well. It' just the BasicClient that stays the same.

Yes, I think so too because this data is really Parsec specific.

**Pull request merged**
