### PR TITLE
Update interface to pick up prost bump

### PR DESCRIPTION
**Pull request by ionut-arm**
Signed-off-by: Ionut Mihalcea <ionut.mihalcea@arm.com>

### CODE REVIEW

**Review by hug-dev — APPROVED** [review]
🥂

**Comment by ionut-arm** [comment]
> 
> 
> 🥂

Wait a second - do we not have the same requirements for the client, the same compiler requirements?

And secondly, I'll have to cancel this PR and revert the change in `parsec-interface`, because otherwise we won't be able to use it in the service.

**Comment by hug-dev** [comment]
Yes, I guess so, we have the same requirement everywhere 😞 We should probably add it to the CI of all of our crates, otherwise we will discover it too late everytime...

**Comment by ionut-arm** [comment]
Closing as it will be fixed by #88

**Pull request closed without merging**
