### PR TITLE
Bump Crates' versions

### PR DESCRIPTION
**Pull request by mohamedasaker-arm**
Signed-off-by: Mohamed Omar Asaker <mohamed.omarasaker@arm.com>

### CODE REVIEW

**Comment by ionut-arm** [comment]
Changelog?

**Comment by mohamedasaker-arm** [comment]
It will follow after I create the tag on this pr, otherwise, it will be generated with "Unreleased" at the top
and then move the tag.

**Comment by mohamedasaker-arm** [comment]
no, it will be included, I will move the tag to the commit that includes the changelog
So, If I am not doing it this way. which commit should I put the tag on? if the HEAD, then it will not include bumping crates versions in the change log

**Comment by mohamedasaker-arm** [comment]
Hmm, I think I misunderstood your statement. 
I think you want the changelog to have the PR containing the changes of the changelog
Now I wonder how is it possible.
So I am a bit puzzled 😅.

**Comment by ionut-arm** [comment]
Ah, no, all I want to make sure is that the final tag covers the changelog as well, regardless of how that's achieved. If you want to push it in a separate PR that's fine by me!

**Comment by mohamedasaker-arm** [comment]
Yes, I will follow this PR with the changelog updates

**Review by ionut-arm — APPROVED** [review]

**Pull request merged**
